#%RAML 1.0 NamedExample

Order:
  application/json:
    examples: |
      {
        "order_id": "628e4bd5f032395b1300013a",
        "qty": "5",
        "datetime": "5/15/2022",
        "store_id": "3",
        "product_id": z"cf3705e6-ab30-43e3-89d4-ffedeb559af0",
        "txn_id": "628e4bbcf032395e5f000110"
      },
      {
        "order_id": "628e4bd5f032395b1300013b",
        "qty": "9",
        "datetime": "4/25/2022",
        "store_id": "2",
        "product_id": "cecc3fca-98cb-4465-b48f-c62ecc53fbe7",
        "txn_id": "628e4bbcf032395e5f000100"
      },
      {
        "order_id": "628e4bd5f03239591000014d",
        "qty": "5",
        "datetime": "3/28/2022",
        "store_id": "4",
        "product_id": "072a4b81-06bd-425d-b528-6cca87bc7c6a",
        "txn_id": "628e4bbcf032395e5f00010b"
      }
    
  